import { describe, expect } from 'vitest';
import * as byegl from '../src/index.ts';
import { $internal } from '../src/types.ts';
import { ByeGLUniformLocation } from '../src/uniform.ts';
import { test, toWgsl } from './extendedTest.ts';

function extractUniformInfo(location: WebGLUniformLocation | null) {
  if (!location) {
    return null;
  }
  const internal = (location as ByeGLUniformLocation)[$internal];

  return {
    location: internal.baseInfo.location,
    byteOffset: internal.byteOffset,
    dataType: String(internal.dataType),
  };
}

describe('float uniform', () => {
  test('shader generation', ({ gl }) => {
    const glslVert = `
      uniform float uFoo;
    `;

    const glslFrag = `
      uniform float uBar;
    `;

    const { wgsl } = toWgsl(gl, glslVert, glslFrag);

    expect(wgsl).toMatchInlineSnapshot(`
      "// Generated by byegl

      var<private> gl_Position: vec4<f32>;
      var<private> gl_FragColor: vec4<f32>;

      @group(0) @binding(0) var<uniform> uFoo: f32;
      @group(0) @binding(1) var<uniform> uBar: f32;

      struct _byegl_VertexOut_2 {
        @builtin(position) _byegl_posOut_3: vec4f,

      }


      @vertex
      fn _byegl_vert_main_4() -> _byegl_VertexOut_2 {


        _byegl_fake_vertex_0();
        var output: _byegl_VertexOut_2;
        output._byegl_posOut_3 = gl_Position;
        // NOTE: OpenGL uses z in the range [-1, 1], while WebGPU uses z in the range [0, 1].
        output._byegl_posOut_3.z = output._byegl_posOut_3.z * 0.5 + 0.5;

        return output;
      }

      @fragment
      fn _byegl_frag_main_5() -> @location(0) vec4f {
        // Filling proxies with varying data

        _byegl_fake_fragment_1();
        return gl_FragColor;
      }
      "
    `);
  });
});

describe('WGSL Generator - separate function names', () => {
  test('Produce vertex and fragment functions with mangled names', ({ gl }) => {
    const glslVert = `
      float foo() { return 1.0; }
      float foo(float v) { return v + 1.0; }
      float foo(int v) { return float(v) + 2.0; }
      vec4 foo_f32(float v) { return vec4(v); }
      void main() { gl_Position = vec4(foo()); }
    `;
    const glslFrag = `
      float foo() { return 2.0; }
      void main() { gl_FragColor = vec4(foo()); }
    `;

    const vert = gl.createShader(gl.VERTEX_SHADER)!;
    gl.shaderSource(vert, glslVert);
    const frag = gl.createShader(gl.FRAGMENT_SHADER)!;
    gl.shaderSource(frag, glslFrag);
    const program = gl.createProgram();
    gl.attachShader(program, vert);
    gl.attachShader(program, frag);
    gl.linkProgram(program);

    const wgsl = byegl.getWGSLSource(gl, program);

    expect(wgsl).toMatchInlineSnapshot(`
      "// Generated by byegl

      var<private> gl_Position: vec4<f32>;
      var<private> gl_FragColor: vec4<f32>;


      fn foo_vertex() -> f32 {
        return 1.0;
      }

      fn foo_f32_1(v: f32) -> f32 {
        return v + 1.0;
      }
      
      fn foo_i32(v: i32) -> f32 {
        return f32(v) + 2.0;
      }

      fn foo_f32(v: f32) -> vec4f {
        return vec4f(v);
      }

      fn _byegl_fake_vertex_0() {
        gl_Position = vec4f(foo_vertex());
      }

      fn foo_fragment() -> f32 {
        return 2.0;
      }

      fn _byegl_fake_fragment_1() {
        gl_FragColor = vec4f(foo_fragment());
      }

      struct _byegl_VertexOut_2 {
        @builtin(position) _byegl_posOut_3: vec4f,

      }


      @vertex
      fn _byegl_vert_main_4() -> _byegl_VertexOut_2 {


        _byegl_fake_vertex_0();
        var output: _byegl_VertexOut_2;
        output._byegl_posOut_3 = gl_Position;
        // NOTE: OpenGL uses z in the range [-1, 1], while WebGPU uses z in the range [0, 1].
        output._byegl_posOut_3.z = output._byegl_posOut_3.z * 0.5 + 0.5;

        return output;
      }

      @fragment
      fn _byegl_frag_main_5() -> @location(0) vec4f {
        // Filling proxies with varying data

        _byegl_fake_fragment_1();
        return gl_FragColor;
      }
      "
    `);
  });
});

describe('getUniformLocation', () => {
  test('basic uniform location', ({ gl }) => {
    const glslVert = `
      uniform float u_foo;
    `;

    const glslFrag = `
      uniform float u_bar;
      uniform vec3 u_vec3;
      uniform mat4 u_mat4;

      void main() {
        gl_FragColor = vec4(u_bar + u_foo + u_vec3.x + u_mat4[0][0]);
      }
    `;

    const { program } = toWgsl(gl, glslVert, glslFrag);

    // Test basic uniform access
    const fooLocation = gl.getUniformLocation(program, 'u_foo');
    expect(extractUniformInfo(fooLocation)).toMatchInlineSnapshot(`
      {
        "byteOffset": 0,
        "dataType": "f32",
        "location": 0,
      }
    `);

    // Test vec3 uniform access
    const vec3Location = gl.getUniformLocation(program, 'u_vec3');
    expect(extractUniformInfo(vec3Location)).toMatchInlineSnapshot(`
      {
        "byteOffset": 32,
        "dataType": "vec3f",
        "location": 0,
      }
    `);

    // Test mat4 uniform access
    const mat4Location = gl.getUniformLocation(program, 'u_mat4');
    expect(mat4Location).not.toBeNull();
    expect(extractUniformInfo(mat4Location)).toMatchInlineSnapshot(`
      {
        "byteOffset": 48,
        "dataType": "mat4x4f",
        "location": 0,
      }
    `);
  });

  test('array and struct access', ({ gl }) => {
    const glsl = `
      precision mediump float;

      struct Light {
        vec3 position;
        vec3 color;
      };

      uniform Light u_light[2];
      uniform vec3 u_colors[2];

      void main() {
        // Use the uniforms to ensure they're not optimized away
        vec3 color = u_light[0].color + u_light[1].color + u_colors[0] + u_colors[1];
        gl_FragColor = vec4(color, 1.0);
      }
    `;

    const { program } = toWgsl(gl, glsl);

    // Structs themselves don't get locations, only primitives
    expect(
      extractUniformInfo(gl.getUniformLocation(program, 'u_light[0]')),
    ).toMatchInlineSnapshot(`null`);

    expect(
      extractUniformInfo(gl.getUniformLocation(program, 'u_light[0].position')),
    ).toMatchInlineSnapshot(`
      {
        "byteOffset": 0,
        "dataType": "vec3f",
        "location": 0,
      }
    `);

    expect(
      extractUniformInfo(gl.getUniformLocation(program, 'u_light[1].color')),
    ).toMatchInlineSnapshot(`
      {
        "byteOffset": 48,
        "dataType": "vec3f",
        "location": 0,
      }
    `);

    expect(
      extractUniformInfo(gl.getUniformLocation(program, 'u_colors[0]')),
    ).toMatchInlineSnapshot(`
      {
        "byteOffset": 64,
        "dataType": "vec3f",
        "location": 0,
      }
    `);

    expect(
      extractUniformInfo(gl.getUniformLocation(program, 'u_colors[1]')),
    ).toMatchInlineSnapshot(`
      {
        "byteOffset": 80,
        "dataType": "vec3f",
        "location": 0,
      }
    `);
  });
});
