import * as d from 'typegpu/data';
import { WgslGenerator, WgslGeneratorResult } from './wgsl-generator.ts';

export class MockWGSLGenerator implements WgslGenerator {
  generate(_vertexCode: string, _fragmentCode: string): WgslGeneratorResult {
    return {
      wgsl: `
        // Generated by byegl

        @vertex
        fn main_vert(@location(0) a_position: vec2f) -> @builtin(position) vec4f {
          return vec4f(a_position * 0.5, 0.0, 1.0);
        }

        @fragment
        fn main_frag() -> @location(0) vec4f {
          return vec4f(1);
        }
      `,
      attributes: [{ id: 'a_position', location: 0, type: d.vec4f }],
      uniforms: [],
      textureUniforms: [],
      samplerToTextureMap: new Map(),
      uniformBufferLayout: undefined,
    };
  }
}
