import * as shaderkit from '@iwoplaza/shaderkit';
import { WgslGenerator } from './wgsl-generator.ts';

export class ShaderkitWGSLGenerator implements WgslGenerator {
  generate(vertexCode: string, fragmentCode: string): string {
    const vertexAst = shaderkit.parse(vertexCode);
    const fragmentAst = shaderkit.parse(fragmentCode);

    return `
      // Generated by degl

      ${vertexCode}
      ${fragmentCode}
    `;
  }
}
