import * as shaderkit from 'shaderkit';

export function generate(
  vertexAst: shaderkit.Program,
  fragmentAst: shaderkit.Program,
): string {
  // TODO: Implement the generate function
  return `
    // Generated by degl

    @vertex
    fn main_vert(@location(0) a_position: vec2f) -> @builtin(position) vec4f {
      return vec4f(a_position * 0.5, 0.0, 1.0);
    }

    @fragment
    fn main_frag() -> @location(0) vec4f {
      return vec4f(1);
    }
  `;
}
